version: '3'

services:
  binance:    
    image: binance-producer:latest
    hostname: binance
    container_name: binance
    ports:    
      - 8090:8080
    networks:
      - streaming
    depends_on:    
      - kafka
    environment:
      TOPIC: crypto-prices
      BOOTSTRAP_SERVERS: kafka:9092
    env_file:
      - .env

#  viewer:    
#   image: streaming-viewer:latest
#   hostname: viewer
#   container_name: viewer
#   ports:    
#     - 8082:8080
#   networks:    
#     - streaming
#   depends_on:    
#     - kafka
#   environment:    
#     - QUARKUS_HTTP_PORT=8080    

  zookeeper:
    image: quay.io/strimzi/kafka:0.21.1-kafka-2.7.0
    hostname: zookeeper
    container_name: zookeeper
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
      ]
    networks:
      - streaming
    ports:
      - 2181:2181
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: quay.io/strimzi/kafka:0.21.1-kafka-2.7.0
    hostname: kafka
    container_name: kafka
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - streaming
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

networks:
  streaming:
    driver: bridge
    ipam:
      driver: default
